image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: >
       echo "creating assessment... $ASSESSMENT_REPO" 
       && cd /workspace/assessment
       && ./.prepare.sh
       && echo "done."
    command: gp open README.md && echo "ready!"

workspaceLocation: "assessment"    
checkoutLocation: "assessment"

vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-pack
    - muhammad-sammy.csharp
    - fwcd.kotlin
    - richardwillis.vscode-gradle
    - kevgo.vscode-markdown-ide
    - moog.sqlnotebook
    - andrewmcodes.rails-extension-power-pack
    - wesleyegberto.vscode-java-tests
    - cweijan.vscode-database-client2
    - hashicorp.terraform
    - scalameta.metals
    - gengjiawen.npm-dependency-link
    - vscode.npm
    - christian-kohler.npm-intellisense
    - gamunu.vscode-yarn
    
    
