image:
  file: .gitpod.Dockerfile

ports:
  - port: 3000
    onOpen: open-preview
  - port: 8080
    onOpen: open-preview
  - port: 9000
    onOpen: open-preview
  - port: 8828 # Gradle daemon
    onOpen: ignore

tasks:
  - init: >
       echo "creating assessment... $ASSESSMENT_REPO" 
       && cd /workspace/assessment
       && ./.prepare.sh
       && echo "done."
  - command: gp open README.md && echo "ready!"

workspaceLocation: "assessment"    
checkoutLocation: "assessment"

vscode:
  extensions:
    - muhammad-sammy.csharp
    - redhat.java
    - vscjava.vscode-java-pack
    - fwcd.kotlin
    - richardwillis.vscode-gradle
    - kevgo.vscode-markdown-ide
    - moog.sqlnotebook
    - andrewmcodes.rails-extension-power-pack
    - wesleyegberto.vscode-java-tests
    - cweijan.vscode-database-client2
    - hashicorp.terraform
    - scalameta.metals
    - gengjiawen.npm-dependency-link
    - vscode.npm
    - christian-kohler.npm-intellisense
    - gamunu.vscode-yarn
    
github:
  prebuilds:
    master: false
    branches: false
    pullRequests: false
    pullRequestsFromForks: false
    addCheck: false
    addComment: false
    addBadge: false    
